//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajeros
    {
        public int id { get; set; }
        public int Id_vuelo { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int Visa { get; set; }
        public Nullable<int> Pasaporte { get; set; }
    }
}
